{% set name = "sparseconverter" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sparseconverter-{{ version }}.tar.gz
  sha256: 5783e2ed236d15023a18d654b1e2617b444e91e3189c3bde66c664dd0e5df8bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy <1.11
    - sparse >=0.12
    - typing-extensions

test:
  imports:
    - sparseconverter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LiberTEM/sparseconverter
  summary: Sparse array type conversion utility
  license: MIT
  license_file: LICENSE
  description: |
    Converter matrix and type determination for
    a range of array formats, focusing on sparse arrays

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
